### ISSUE TITLE
Fails when the package is not present in the base branch

### ISSUE THREAD

**Issue by dcu** [knqyf263/cob#11]
I passed `--base=origin/master` and now I'm getting:

```
2020/01/15 15:44:23 failed to run a benchmark: failed to run 'go test -run '^$' -bench . -benchmem ./mypkg' command: exit status 1
```

Because there are no benchmarks yet in the base. I believe this is a regression since I don't remember seeing this error before.

I fixed it by adding a `git grep` command in the pipeline script but it'd be great if this tool did that

**Comment by knqyf263** [comment]
@dcu Thank you for the report! I fixed it at v0.0.4.
