### ISSUE TITLE
Allow to pass the base commit

### ISSUE THREAD

**Issue by dcu** [knqyf263/cob#4]
By default, cob uses @{1} as base commit but in my pipeline I'd like to compare against `origin/master`, one reason is that right now you can make a change that's worse and then make a commit without fixing it and it'll use the previous commit (the bad one) to compare against the new commit (that's equally bad) ... skipping the check

**Comment by knqyf263** [comment]
It makes sense. I'll try it.

**Comment by knqyf263** [comment]
I implemented it. I will release a new version later.
